export const ROUTES = {
  INDEX: '/',
  WELCOME: '/(auth)/welcome',
  LOGIN: '/(auth)/login',
  REGISTER: '/(auth)/register',
  FORGOT_PASSWORD: '/(auth)/forgot-password',
  HOME: '/(customer)/(tabs)/',
  SEARCH: '/(customer)/(tabs)/search',
  ORDERS: '/(customer)/(tabs)/orders',
  PROFILE: '/(customer)/(tabs)/profile',
  FOOD: '/(customer)/food/[id]',
  COMBO: '/(customer)/combo/[id]',
  CART: '/(customer)/cart',
  CHECKOUT: '/(customer)/checkout',
  ADDRESSES: '/(customer)/addresses',
  ADD_ADDRESS: '/(customer)/addresses/add',
  FAVORITES: '/(customer)/favorites',
  COUPON: '/(customer)/cupon',
  NOTIFICATIONS: '/(customer)/notification',
  SUPPORT: '/(customer)/support',
  ORDER_CONFIRMATION: '/(customer)/order-conformation/[id]',
  ORDER_TRACKING: '/(customer)/order-tracking/[id]',
  REVIEW: '/(customer)/review/[id]',
  ADMIN_HOME: '/(admin)/(tabs)/',
  DRIVER_HOME: '/(driver)/(tabs)/',
} as const;
